### ISSUE TITLE
Potential/ confirmed concurrency issues

### ISSUE THREAD

**Issue by csegarragonz** [faasm/faabric#189]
This issue is a list of all the potentially/ confirmed dodgy bits of concurrent code.

Useful links:

- [Clang TS analysis](https://clang.llvm.org/docs/ThreadSafetyAnalysis.html)
- [C++ memory order](https://en.cppreference.com/w/cpp/atomic/memory_order)
- [C++ memory model](https://en.cppreference.com/w/cpp/language/memory_model)

## Miscellaneous

- [ ] Reading from a variables without taking a lock, while writing to it through a mutex. Instead, wrap single variables in an atomic, and use acquire/release accesses. For groups of variables, make sure to take a shared lock. 
- [ ] Double locking without atomic accesses (i.e. `if(!x) {lock(); if(!x) {}}` if `x` is not atomic). Instead make `x` atomic.
- [ ] Use of maps as registries for looking up objects like snapshots, distributed coordination groups, and message queues. These are accessed concurrently and often include some lazy-initialisation, all of which is guarded by mutexes scattered around the place. Could experiment with concurrent containers such as [`libcds`](https://github.com/khizmax/libcds) and [`phmap`](https://github.com/greg7mdp/parallel-hashmap). 
- [ ] Returning map values without an associated lock: often some `cacheMap.get(key)` operation is protected by a mutex (or in the future a concurrent hash map), but if it returns a reference or pointer, `cacheMap.clear()` from another thread can invalidate that reference. Make sure to either return `std::shared_ptr`s where appropriate, or a pair of a reference with a `SharedLock` on the entire cache to make sure nothing can invalidate that reference while it's being used outside the `get` implementation.

## Thread sanitizer

List of known issues raised by the thread sanitiser, together with details to fix them. 

## Leak sanitizer

- [ ] Segmentation fault in snapshot test [`"TEST: Test snapshot diffs with merge ops"`](https://github.com/faasm/faabric/runs/4504435160?check_suite_focus=true#step:10:1200).
- [ ] Wrong test result in test [`"TEST: Test direct messaging"`](https://github.com/faasm/faabric/runs/4739026659?check_suite_focus=true#step:11:1828)

**Comment by kubasz** [comment]
For the first one: take a shared lock in getLockOwner(), alternatively convert the lockOwnerIdx to an atomic int and do acquire loads/release stores (free on x86_64)
