### ISSUE TITLE
LeakSan tests taking a very long time

### ISSUE THREAD

**Issue by eigenraven** [faasm/faabric#276]
Just looking at recent actions logs, it looks like there's a lot of 30s sleeps between tests that for some reason only happen when testing with the Leak santitizer enabled.

**Comment by csegarragonz** [comment]
According to the [docs](https://clang.llvm.org/docs/LeakSanitizer.html) the leak sanitizer should:
* Add no overhead.
* Be enabled by default with Address Sanitizer.

Do you know what could be happening then?

**Comment by eigenraven** [comment]
I have no idea, but if asan can already cover it we can probably just remove independent leaksan. The docs do say it is a much less tested/supported configuration.
